### ISSUE TITLE
inconsistent byte length of hash code

### ISSUE THREAD

**Issue by qinzuoyan** [imzhenyu/rDSN#508] opened 2016-08-02 06:23 UTC
Hash code is mainly used for two purposes: partition hash and thread hash.

The _hash_ field in message_header is an important value: before partition resolving, it's the partition hash set by user; after partition resolving, it's the thread hash passing to server to determine which thread to dispatch.

```
typedef struct message_header
{
    ....
    struct
    {
        uint64_t hash; // for both partition hash and thread hash for the exact location of this request
        int32_t  timeout_ms;
        int32_t  padding;
    } client;
    ....
} message_header;
```

Firstly, we calculate partition hash by rrdb_key_hash() in client:

```
inline uint64_t rrdb_key_hash(const ::dsn::blob& key)
{
    dassert(key.length() >= 2, "key length must be greater than 2");

    // hash_key_len is in big endian
    uint16_t hash_key_len = be16toh(*(int16_t*)(key.data()));

    if (hash_key_len > 0)
    {
        // hash_key_len > 0, compute hash from hash_key
        dassert(key.length() >= 2 + hash_key_len, "key length must be greater than (2 + hash_key_len)");
        return dsn_crc64_compute(key.buffer_ptr() + 2, hash_key_len, 0);
    }
    else
    {
        // hash_key_len == 0, compute hash from sort_key
        return dsn_crc64_compute(key.buffer_ptr() + 2, key.length() - 2, 0);
    }
}
```

When partition resolving, we calculate partition index from partition_count and partition_hash:

```
int partition_resolver_simple::get_partition_index(int partition_count, uint64_t partition_hash)
{
    return partition_hash % static_cast<uint64_t>(partition_count);
}
```

After partition resolving, we reset client.hash to value of dsn_gpid_to_hash(), which will be passed to replica server:

```
    resolver->resolve(
        partition_hash,
        [=](dist::partition_resolver::resolve_result&& result) mutable
        {
            if (result.err == ERR_OK)
            {
                // update gpid when necessary
                auto& hdr2 = request->header;
                if (hdr2->gpid.value != result.pid.value)
                {
                    dassert(hdr2->gpid.value == 0, "");
                    hdr2->gpid = result.pid;
                    hdr2->client.hash = dsn_gpid_to_hash(result.pid);
                }

                call_address(result.address, request, call);
            }
            else
            {                        
                if (call != nullptr)
                {
                    call->enqueue(result.err, nullptr);
                }
                else
                {
                    // as ref_count for request may be zero
                    request->add_ref();
                    request->release_ref();
                }
            }
        },
        hdr.client.timeout_ms
        );
```

The dsn_gpid_to_hash() is implemented as:

```
inline uint64_t dsn_gpid_to_hash(dsn_gpid gpid)
{
    return (((uint64_t)gpid.u.app_id) << 32) + gpid.u.partition_index;
}
```

All the above hash codes are stored as _uint64_t_, there is no problem.

But unfortunately, the hash code in task is stored as _int_:

```
class task
{
public:
    DSN_API task(
        dsn_task_code_t code, 
        void* context, 
        dsn_task_cancelled_handler_t on_cancel, 
        int hash = 0, 
        service_node* node = nullptr
        );
    int                     hash() const { return _hash; }
private:
    int                    _hash;
```

We create _rpc_request_task_ from _message_ex_, **casting hash code from uint64_t to int**, which will discard the high bytes, and only leave the low bytes (just equals to _gpid.partition_index_).

```
rpc_request_task::rpc_request_task(message_ex* request, rpc_handler_info* h, service_node* node)
    : task(dsn_task_code_t(h->code),  // it is possible that request->local_rpc_code != h->code when it is handled in frameworks
        nullptr, 
        [](void*) { dassert(false, "rpc request task cannot be cancelled"); },
        static_cast<int>(request->header->client.hash),
        node)
{}
```

The _task_worker_pool_ will dispatch the task according to the hash:

```
void task_worker_pool::enqueue(task* t)
{
    dassert(t->spec().pool_code == spec().pool_code || t->spec().type == TASK_TYPE_RPC_RESPONSE, 
        "Invalid thread pool used");
    dassert(t->delay_milliseconds() == 0,
        "task delayed should be dispatched to timer service first");

    if (_is_running)
    {
        int idx = (_spec.partitioned ? t->hash() % _queues.size() : 0);        
        return _queues[idx]->enqueue_internal(t);
    }
    else
    {
        dassert (false, "worker pool %s must be started before enqueue task %s",
            spec().name.c_str(),
            t->spec().name.c_str()
            );
    }
}
```

So the problem is: we use inconsistent byte length of hash code, making task dispatching determined only by _gpid.partition_index_, which I think is not proper.

I suggest using consistent type (uint64_t) of hash code.

**Comment by imzhenyu** [comment] 2016-08-02 07:21
@qinzuoyan Your understanding about the hash is correct, and the task uses hash as an integer because it is a local behavior now, as it is used only for thread dispatching. The machine/partition dispatch part is used in messages. Changing the task hash to uint64 is kind of too heavy for the local tasks (e.g., timers, lpcs, rpc response tasks, aio tasks). Maybe we can change the inline or static-cast function with a more meaningful name, e.g., `global_hash_to_thread_hash`.

**Comment by qinzuoyan** [comment] 2016-08-02 07:30
now dispatch just by partition_index may cause thread load balance problem,
for example, replicas with the same partition_index (even with different
app_id) will be dispatched to the same thread.

**Comment by imzhenyu** [comment] 2016-08-02 07:32
These two problems are orthogonal, as even you use uint64 for task hash, the thread dispatching will still go to the same result (e.g., when thread number for replication thread pool is 8). For load balance issue, you may change the logic inside `global_hash_to_thread_hash`, e.g., return partition_index + app_id, or something like that.

**Comment by qinzuoyan** [comment] 2016-08-02 08:11
but the problem is, in many places, we just use implicitly cast from uint64_t to int:

```
    _potential_secondary_states.learn_remote_files_completed_task = tasking::create_task(
        LPC_LEARN_REMOTE_DELTA_FILES_COMPLETED,
        this,
        [this, err]()
        {
            on_learn_remote_state_completed(err);
        },
        gpid_to_hash(get_gpid())
        );
```

if we use _global_hash_to_thread_hash()_ liked function instead of implicit-cast, then there is risk that when we forget using the function, the compiler will just use implicit-cast and can not give warning. It is hard to maintain.

**Comment by imzhenyu** [comment] 2016-08-02 08:22
The maintenance is indeed an issue.  Let's do the following then: 
- use uint64_t for all hash value as you suggested, but this won't fix the load balance problem
- change dsn_gpid_to_hash to fix LB issue.

**Comment by qinzuoyan** [comment] 2016-08-02 08:25
I think the later is better, we can return a uint32_t compatible value for dsn_gpid_to_hash(). Moreover, for better load balance, we'd better not simply combine app_id and partition_index like _((app_id << 16) + partition_index)_.

**Comment by qinzuoyan** [comment] 2016-08-03 04:09
@imzhenyu , I found a problem.

We use message_header.client.hash for both partition_hash and thread_hash, storing different value on different time range, just as above. But it may cause miss-use if not careful, and bring in tricky problem.

For example, in rpc_engine.cpp:866, we will do retry RPC re-using the old message. Think about the case that the message has been resolved **partly** succeed: the gpid is known and the _message_header.client.hash_ had been set to thread hash, but the primary_address is invalid. But the next dsn_rpc_call() will treat _message_header.client.hash_ as partition hash, which will cause tricky error.

The problem is not found before because we always set partition_count to 2^x, and calculate thread_hash by dsn_gpid_to_hash(), which is _(app_id << 32) + partition_index_, so the partition_index will always the same. But when we change dsn_gpid_to_hash() to _app_id + partition_index_, the partition_index will not be the same.

My suggestion is: use different field to store different hash in message_header.

```
struct message_header {
        ....
        struct
        {
            uint64_t partition_hash; // partition hash used for calculating partition index
            int32_t  timeout_ms;     // rpc timeout in milliseconds
            int32_t  thread_hash;    // thread hash used for thread dispatching
        } client;
        ....
};
```

**Comment by imzhenyu** [comment] 2016-08-03 04:47
Right, so the problem is caused by the overwritten of the hash value in message header. I think your suggestion is reasonable. We may also need to change the APIs in that case, i.e., adding partition_hash and thread_hash as two separated parameters for the rpc-call related APIs. You may do that together. Thx.

**Comment by qinzuoyan** [comment] 2016-08-03 04:58
Working on it ...

**Comment by qinzuoyan** [comment] 2016-08-03 05:11
And why need we use uint64_t to store partition_hash? or also use int can be ok?

**Comment by imzhenyu** [comment] 2016-08-03 05:13
The goal is to have a big enough value range so that latter on we may enable range partition, consistent hash, etc.

**Comment by imzhenyu** [comment] 2016-08-15 04:58
Close now since it is done.

**Closed as completed by imzhenyu** 2016-08-15 04:58 UTC
Labels: enhancement
