### ISSUE TITLE
a bug of usage of update_init_info in learning process, which may cause data lost 

### ISSUE THREAD

**Issue by qinzuoyan** [imzhenyu/rDSN#405] opened 2016-06-16 09:42 UTC
if data in private buffer is not flushed info file, but log_start_offset is updated in init-info file.

fixed in v0.95, refer to https://github.com/imzhenyu/rDSN/commit/d06d51291d6616146c3805c76497ea6551902cef

**Comment by imzhenyu** [comment] 2016-06-20 02:45
Thanks, @qinzuoyan. Will look into this when the merge is done.

**Comment by imzhenyu** [comment] 2016-06-20 06:25
There is indeed an issue there - however, the fix is not necessarily correct to me. The issue is mostly raised by the non-atomic operations of update_init_info and app::flush, in between those two there are possibly other private log writtens by 2pc with potential secondary. We can discuss in details later.

**Comment by qinzuoyan** [comment] 2016-06-20 06:30
Yes, the fix is probably not correct, and I have got coredump when re-run
with the fixed code.
And, another problem is: replica::on_copy_remote_state_completed() is
running in REPLICATION_LONG thread, and at the mean time commit may be
doing in REPLICATION thread, which will cause problem.
So need more careful fix.

**Comment by imzhenyu** [comment] 2016-06-20 06:33
The thread interleaving is done intentionally. The idea is to catch-up with the secondaries for potential secondaries using 2pc, while at the same time we are doing state checkpointing in on_copy_remote_state_completed.

**Comment by imzhenyu** [comment] 2016-06-27 02:22
Current test shows the bug is gone - i'm closing the issue now and  will reopen if further more test reproduces this problem again.

**Closed as completed by imzhenyu** 2016-06-27 02:22 UTC
